# Use an official Node runtime as the base image
FROM node:latest as build

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the app
RUN npm run build

# Use Nginx to serve the build folder
FROM nginx:1.19

# Copy the build output to replace the default nginx contents
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 90

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
